### ISSUE TITLE
Shake key throw issue  in  listview.builder 

### ISSUE THREAD

**Issue by mrugesha8** [dheeraj-bhadoria/Flutter-shake-my-widget#1]
**Duplicate GlobalKey detected in widget tree.**

This is My Code ::::

final shakeKey = **GlobalKey<ShakeWidgetState>();**

ListView.builder(
              scrollDirection: Axis.vertical,
              shrinkWrap: true,
              itemCount: 2,
              itemBuilder: (BuildContext context, int index) {
                return GestureDetector(
                  onTap: () {
                    shakeKey.currentState?.shake();
                  },
                  child: ShakeMe(
                    key: shakeKey,
                    shakeCount: 1,
                    shakeOffset: 10,
                    shakeDuration: Duration(milliseconds: 500),
                    // 6. Add the child widget that will be animated
                    child: Padding(
                      padding: const EdgeInsets.all(20),
                      child: Container(color: Colors.red,width: 200,height: 200),
                    ),
                  ),
                );
              },
            )

**Comment by dheeraj-bhadoria** [comment]
Hi @mrugesha8 

Please try the following code 
```

ListView.builder(
  scrollDirection: Axis.vertical,
  shrinkWrap: true,
  itemCount: 2,
  itemBuilder: (BuildContext context, int index) {
    // Generate a unique key for each item using index
    final shakeKey = GlobalKey();
    return GestureDetector(
      onTap: () {
        shakeKey.currentState?.shake();
      },
      child: ShakeMe(
        key: shakeKey,
        shakeCount: 1,
        shakeOffset: 10,
        shakeDuration: Duration(milliseconds: 500),
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Container(color: Colors.red, width: 200, height: 200),
        ),
      ),
    );
  },
)
```

**Comment by mrugesha8** [comment]
Thank You @dheeraj-bhadoria for your support .
